language: php
sudo: false
matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly
cache:
  directories:
    - $HOME/.composer/cache/files
install: make ci-install
script: make ci

