language: php
matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
      env: PHP_CS_FIXER_IGNORE_ENV=1
  fast_finish: true
  allow_failures:
    - php: nightly
install: make ci-install
script: make ci
