name: CI (scheduled)
on:
  schedule:
  - cron: 0 14 * * 0 # Sunday 2PM UTC = Monday 12AM AEST
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        coverage: none
    - name: Check PHP version
      run: php -v
    - name: Install dependencies
      run: make vendor
    - name: Check Kahlan Version
      run: vendor/bin/kahlan --no-header --version
    - name: Make
      run: make ci
